/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_bodega;

import java.awt.CardLayout;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.util.JRLoader;
//import net.sf.jasperreports.view.JasperViewer;

/**
 *jdbc:postgresql://localhost:5432/Bodega
 * @author Luiz
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    Tabla_PedidosCompletos tp = new Tabla_PedidosCompletos();
    Modificaciones mod = new Modificaciones();
    Tabla_maestra tbm = new Tabla_maestra();
    Pedido_nuevo pd = new Pedido_nuevo();
    Tabla_maestra_Pedidos Tpd = new Tabla_maestra_Pedidos();
    Pedidos p = new Pedidos();
    
    Tabla t = new Tabla();
    public Pantalla() {
        p.p=this;
        initComponents();
        actualizar_tabla();
        mod.p=this;
    }
    public void actualizar_tabla(){
         t.ver_tabla(tabla_vista,"SELECT nombre, tipo, marca, peso, precio FROM public.vistaproducto;");
    }
    
    public boolean isValidName(String name)
{
    String specialCharacters="!#$%&'*+,-./:;<=>?@[]^_`{|}~0123456789";
    String str2[]=name.split("");
    int count=0;
    for (int i=0;i<str2.length;i++)
    {
        if (specialCharacters.contains(str2[i]))
        {
            count++;
        }
    }       

    if (name!=null && count==0 )
    {
        return true;
    }
    else
    {
        return false;
        
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_vista = new javax.swing.JTable();
        Botones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        PanelCards = new javax.swing.JPanel();
        Altas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_nombre25 = new javax.swing.JLabel();
        Alta_nombreProducto = new javax.swing.JTextField();
        lbl_nombre26 = new javax.swing.JLabel();
        lbl_nombre27 = new javax.swing.JLabel();
        Alta_Marca = new javax.swing.JTextField();
        lbl_nombre28 = new javax.swing.JLabel();
        Alta_Tipo = new javax.swing.JComboBox<>();
        Alta_PEso = new javax.swing.JSpinner();
        lbl_nombre29 = new javax.swing.JLabel();
        Alta_precio = new javax.swing.JSpinner();
        jButton10 = new javax.swing.JButton();
        Consultas = new javax.swing.JPanel();
        con_Nombre_Producto_txt = new javax.swing.JTextField();
        con_Marca = new javax.swing.JTextField();
        con_Tipo = new javax.swing.JComboBox<>();
        con_peso = new javax.swing.JSpinner();
        con_Precio = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        con_rb_NP = new javax.swing.JRadioButton();
        rb_tipo = new javax.swing.JRadioButton();
        rb_marca = new javax.swing.JRadioButton();
        rb_peso = new javax.swing.JRadioButton();
        rb_precio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Pedidos = new javax.swing.JMenuItem();
        Refresh = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor De Bodegas");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 204));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("base-de-datos.png")).getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.SystemColor.activeCaption);
        jLabel1.setText("Productos");

        tabla_vista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nompre Producto", "Tipo producto", "Marca", "Cantidad", "Precio $", "Modificar", "Eliminar", "Pedido nuevo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_vistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_vista);

        Botones.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/busqueda.png"))); // NOI18N
        jButton1.setToolTipText("Panel para buscar registros espesificos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editar.png"))); // NOI18N
        jButton2.setToolTipText("Mostrar panel para agregar nuevos registros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        reset_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/goma-de-borrar.png"))); // NOI18N
        reset_button.setToolTipText("Limpia y reseta consultas y altas");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reset_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelCards.setLayout(new java.awt.CardLayout());

        Altas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Altas");

        lbl_nombre25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre25.setText("Nombre Producto");

        lbl_nombre26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre26.setText("Tipo Producto");

        lbl_nombre27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre27.setText("Marca del Producto");

        lbl_nombre28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre28.setText("Cantidad de producto");

        Alta_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectione una opcion..", "Molido", "Paca", "Grano", "enlatado", "enbotellado", "enpaquetado", "fierro nuevo" }));

        Alta_PEso.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lbl_nombre29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nombre29.setText("Precio Producto");

        Alta_precio.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/subir.png"))); // NOI18N
        jButton10.setToolTipText("Subir a bases de datos");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AltasLayout = new javax.swing.GroupLayout(Altas);
        Altas.setLayout(AltasLayout);
        AltasLayout.setHorizontalGroup(
            AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltasLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addComponent(lbl_nombre28, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta_PEso, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addComponent(lbl_nombre29, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta_precio))
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addComponent(lbl_nombre25, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addComponent(lbl_nombre26, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addComponent(lbl_nombre27, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Alta_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
            .addGroup(AltasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AltasLayout.setVerticalGroup(
            AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltasLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addGroup(AltasLayout.createSequentialGroup()
                        .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alta_nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alta_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alta_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alta_PEso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombre29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Alta_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );

        PanelCards.add(Altas, "card2");

        Consultas.setBackground(new java.awt.Color(204, 204, 204));

        con_Nombre_Producto_txt.setEnabled(false);
        con_Nombre_Producto_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                con_Nombre_Producto_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                con_Nombre_Producto_txtKeyTyped(evt);
            }
        });

        con_Marca.setEnabled(false);
        con_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                con_MarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                con_MarcaKeyTyped(evt);
            }
        });

        con_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectione una opcion..", "Molido", "Paca", "Grano", "enlatado", "enbotellado", "enpaquetado", "fierro nuevo" }));
        con_Tipo.setEnabled(false);
        con_Tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                con_TipoItemStateChanged(evt);
            }
        });

        con_peso.setEnabled(false);
        con_peso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                con_pesoStateChanged(evt);
            }
        });

        con_Precio.setEnabled(false);
        con_Precio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                con_PrecioStateChanged(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/busqueda.png"))); // NOI18N
        jButton5.setToolTipText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar(evt);
            }
        });

        buttonGroup1.add(con_rb_NP);
        con_rb_NP.setText("Nombre Producto");
        con_rb_NP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_rb_NPActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_tipo);
        rb_tipo.setText("Tipo Producto");
        rb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_tipoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_marca);
        rb_marca.setText("Marca");
        rb_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_marcaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_peso);
        rb_peso.setText("Cantidad");
        rb_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_pesoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_precio);
        rb_precio.setText("Precio");
        rb_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_precioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Consultas");

        javax.swing.GroupLayout ConsultasLayout = new javax.swing.GroupLayout(Consultas);
        Consultas.setLayout(ConsultasLayout);
        ConsultasLayout.setHorizontalGroup(
            ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultasLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ConsultasLayout.createSequentialGroup()
                        .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(con_rb_NP)
                            .addComponent(rb_precio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_peso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_marca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_tipo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(con_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_Precio)
                            .addComponent(con_Nombre_Producto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(con_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        ConsultasLayout.setVerticalGroup(
            ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ConsultasLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_Nombre_Producto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(con_rb_NP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_peso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(con_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_precio))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(ConsultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        PanelCards.add(Consultas, "card1");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refrescar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jMenu1.setText("Session");

        jMenuItem2.setText("Cerrar Session");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones avanzadas");

        Pedidos.setText("Pedidos");
        Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidosActionPerformed(evt);
            }
        });
        jMenu2.add(Pedidos);

        Refresh.setText("Recargar Tabla");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jMenu2.add(Refresh);

        jMenuItem5.setText("Grafica productos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Pedidos completados");
        jMenuItem4.setActionCommand("Pedidos completados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Tablas avanzadas Pedidos");
        jMenuItem3.setActionCommand("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3tablaMaestra(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setText("Tablas avanzadas Productos");
        jMenuItem1.setActionCommand("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaMaestra(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 550, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(PanelCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 223, Short.MAX_VALUE)
                    .addComponent(PanelCards, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    grafica g = new grafica();
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        g.obtener_info();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout card =(CardLayout)PanelCards.getLayout();
        card.show(PanelCards, "card2");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         CardLayout card =(CardLayout)PanelCards.getLayout();
        card.show(PanelCards, "card1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void con_rb_NPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_rb_NPActionPerformed
        // TODO add your handling code here:
        con_Nombre_Producto_txt.setEnabled(true);
        con_Marca.setEnabled(false);
        con_Precio.setEnabled(false);
        con_Tipo.setEnabled(false);
        con_peso.setEnabled(false);
    }//GEN-LAST:event_con_rb_NPActionPerformed

    private void rb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_tipoActionPerformed
        // TODO add your handling code here:
        con_Nombre_Producto_txt.setEnabled(false);
        con_Tipo.setEnabled(true);
        con_Marca.setEnabled(false);
        con_peso.setEnabled(false);
        con_Precio.setEnabled(false);
        
    }//GEN-LAST:event_rb_tipoActionPerformed

    private void rb_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_marcaActionPerformed
        // TODO add your handling code here:
        con_Nombre_Producto_txt.setEnabled(false);
        con_Tipo.setEnabled(false);
        con_Marca.setEnabled(true);
        con_peso.setEnabled(false);
        con_Precio.setEnabled(false);
        
    }//GEN-LAST:event_rb_marcaActionPerformed

    private void rb_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_pesoActionPerformed
        // TODO add your handling code here:
        con_Nombre_Producto_txt.setEnabled(false);
        con_Tipo.setEnabled(false);
        con_Marca.setEnabled(false);
        con_peso.setEnabled(true);
        con_Precio.setEnabled(false);
    }//GEN-LAST:event_rb_pesoActionPerformed

    private void rb_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_precioActionPerformed
        // TODO add your handling code here:
        con_Nombre_Producto_txt.setEnabled(false);
        con_Tipo.setEnabled(false);
        con_Marca.setEnabled(false);
        con_peso.setEnabled(false);
        con_Precio.setEnabled(true);
    }//GEN-LAST:event_rb_precioActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
          con_Nombre_Producto_txt.setText("");
        con_Tipo.setSelectedIndex(0);
        con_Marca.setText("");
        con_peso.setValue(0);
        con_Precio.setValue(0);
        
        Alta_nombreProducto.setText("");
        Alta_Tipo.setSelectedIndex(0);
        Alta_Marca.setText("");
        Alta_PEso.setValue(0);
        Alta_precio.setValue(0);
        
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:   
            new InicioSesion().setVisible(true);
              this.dispose();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        mod.setVisible(false);
        boolean validacion=true;
        
        if (!isValidName(Alta_nombreProducto.getText())) {
           validacion=false;
           JOptionPane.showMessageDialog(this,"Campo invalido o vacia en nombre producto","Error",JOptionPane.WARNING_MESSAGE);
        }else if (!isValidName(Alta_Marca.getText())) {
           validacion=false;
           JOptionPane.showMessageDialog(this,"Campo invalido o vacia en marca","Error",JOptionPane.WARNING_MESSAGE);
        }else if (Alta_Tipo.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(this,"Campo invalido o vacia en Tipo","Error",JOptionPane.WARNING_MESSAGE);
        }else if (Alta_precio.getValue().equals(0)) {
          JOptionPane.showMessageDialog(this,"Cantidad no puede ser 0!","Error",JOptionPane.WARNING_MESSAGE);
        }else if (Alta_precio.getValue().equals(0)) {
          JOptionPane.showMessageDialog(this,"Precio no puede ser 0!","Error",JOptionPane.WARNING_MESSAGE);
        }
        if (validacion) {
            if (Alta_nombreProducto.getText().equals("") || Alta_Tipo.getSelectedIndex()==0 || Alta_Marca.getText().equals("") || Alta_PEso.getValue().equals(0) || Alta_precio.getValue().equals(0)) {
             //JOptionPane.showMessageDialog(this,"Campo invalido o vacia","Error",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                ResultSet res = Conexion.Conexion.Consulta("SELECT public.obtenercantidad()");
                res.next();
                //System.out.println("cantidad: "+ res.getInt(1));
                int cantidad =  res.getInt(1);
                if (cantidad==0) {
                        Conexion.Conexion.Ejecutar("INSERT INTO public.productos(" +
"                       idproducto, idnumero, nombre, tipo, marca, peso, precio) VALUES"+" ('PO1'"+",1,"
                        +"'"+Alta_nombreProducto.getText()+"'"+","+"'"+Alta_Tipo.getSelectedItem().toString()+"'"
                        +","+"'"+Alta_Marca.getText()+"'"+","+ Alta_PEso.getValue() +"," + Alta_precio.getValue()+");");
                }else{
                    
                    res = Conexion.Conexion.Consulta("SELECT public.obtenerint()");
                    res.next();
                    cantidad =  res.getInt(1);
                        Conexion.Conexion.Ejecutar("INSERT INTO public.productos(" +
"                       idproducto, idnumero, nombre, tipo, marca, peso, precio) VALUES"+" ('PO"+cantidad+"'"+","+cantidad+","
                        +"'"+Alta_nombreProducto.getText()+"'"+","+"'"+Alta_Tipo.getSelectedItem().toString()+"'"
                        +","+"'"+Alta_Marca.getText()+"'"+","+ Alta_PEso.getValue() +"," + Alta_precio.getValue()+");");
                
                
                }
               
                reset_buttonActionPerformed(evt);
            } catch (Exception e) {
               // System.out.println(e);
                JOptionPane.showMessageDialog(this,"Nombres de productos ya existe en la base de datos","Error",JOptionPane.WARNING_MESSAGE);
            }
        actualizar_tabla();
        }
        }else{
         //JOptionPane.showMessageDialog(this,"Caracteres invalidos","Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed
        int click_tabla;
    private void tabla_vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_vistaMouseClicked
        // TODO add your handling code here:
        click_tabla = this.tabla_vista.rowAtPoint(evt.getPoint());
        
        String NombreProducto = ""+tabla_vista.getValueAt(click_tabla, 0);
        String Tipo_producto = ""+tabla_vista.getValueAt(click_tabla, 1);
        String Marca = ""+tabla_vista.getValueAt(click_tabla, 2);
        double Peso = (double)tabla_vista.getValueAt(click_tabla, 3);
        double Precio = (double)tabla_vista.getValueAt(click_tabla, 4);
        int x=0;
        int column = tabla_vista.getColumnModel().getColumnIndexAtX(evt.getX());
        int Row = evt.getY()/tabla_vista.getRowHeight();
        
        if (Row<tabla_vista.getRowCount() && Row>=0 & column<tabla_vista.getColumnCount() && column>=0) {
            Object value = tabla_vista.getValueAt(Row, column);
            if (value instanceof  JButton) {
                ((JButton)value).doClick();
                JButton button = (JButton) value;
                
                if (button.getName().equals("M")) {
                   mod.setVisible(true);
                   pd.setVisible(false);
                    if (Tipo_producto.equals("Molido")) {
                        x=1;
                    }else if (Tipo_producto.equals("Paca")) {
                        x=2;
                    }else if (Tipo_producto.equals("Grano")) {
                        x=3;
                    }else if (Tipo_producto.equals("enlatado")) {
                        x=3;
                    }else if (Tipo_producto.equals("enbotellado")) {
                        x=3;
                    }else if (Tipo_producto.equals("enpaquetado")) {
                        x=3;
                    }else if (Tipo_producto.equals("Fierro nuevo")) {
                        x=3;
                    }
                   mod.insertar_datos(NombreProducto,x, Marca, Peso, Precio);
                   
                }
                if (button.getName().equals("E")) {
                    mod.setVisible(false);
                    pd.setVisible(false);
                    int n = JOptionPane.showConfirmDialog(  
                    null,
                    "Seguro que quieres eliminar este registro?!\nnombre Producto: " + NombreProducto ,
                    "",
                    JOptionPane.YES_NO_OPTION);
                    
                    if(n == JOptionPane.YES_OPTION)
                    {
                        Conexion.Conexion.Eliminar_Producto("Delete from productos where Nombre='"+NombreProducto+"';");
                        actualizar_tabla();
                        //JOptionPane.showMessageDialog(null, "registro Eliminado");
                    }
            } 
                if (button.getName().equals("P")) {
                        mod.setVisible(false);
                        pd.setVisible(true);
                        pd.insertar_datos(NombreProducto, Tipo_producto, Marca, Peso, Precio);
                    }
        }
    }//GEN-LAST:event_tabla_vistaMouseClicked
 }
    private void tablaMaestra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaMaestra
        // TODO add your handling code here:
        tbm.setVisible(true);
        tbm.actualizarT();
        
    }//GEN-LAST:event_tablaMaestra

    private void Buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar
        // TODO add your handling code here:
        if (con_rb_NP.isSelected()) {
            t.ver_tabla(tabla_vista, "Select * from vistaproducto Where nombre like '%" + con_Nombre_Producto_txt.getText()+"%';");
        }
        if (rb_tipo.isSelected()) {
            if(con_Tipo.getSelectedIndex()!=0)
            t.ver_tabla(tabla_vista, "Select * from vistaproducto Where tipo = '" + con_Tipo.getSelectedItem().toString()+"';");
        }
        if (rb_marca.isSelected()) {
             t.ver_tabla(tabla_vista, "Select * from vistaproducto Where marca Like '%" + con_Marca.getText()+"%';");
        }
        if (rb_peso.isSelected()) {
            if((int)con_peso.getValue()>0){
             t.ver_tabla(tabla_vista, "Select * from vistaproducto Where peso =" + con_peso.getValue()+";");
            }else{
            actualizar_tabla();
            }
        }
        if (rb_precio.isSelected()) {
            if((int)con_Precio.getValue()>0){
             t.ver_tabla(tabla_vista, "Select * from vistaproducto Where precio =" + con_Precio.getValue()+";");
            }else{
            actualizar_tabla();
            }
        }
    }//GEN-LAST:event_Buscar

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        actualizar_tabla();
    }//GEN-LAST:event_RefreshActionPerformed

    private void jMenuItem3tablaMaestra(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3tablaMaestra
        // TODO add your handling code here:
        Tpd.setVisible(true);
        Tpd.actualizarT();
    }//GEN-LAST:event_jMenuItem3tablaMaestra

    private void PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidosActionPerformed
        // TODO add your handling code here:
        p.setVisible(true);
        p.actualizarT();
    }//GEN-LAST:event_PedidosActionPerformed

    private void con_Nombre_Producto_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_Nombre_Producto_txtKeyTyped
        // TODO add your handling code here:
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where nombre like '%" + con_Nombre_Producto_txt.getText()+"%';");
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where nombre like '%" + con_Nombre_Producto_txt.getText()+"%';");
    }//GEN-LAST:event_con_Nombre_Producto_txtKeyTyped

    private void con_MarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_MarcaKeyTyped
        // TODO add your handling code here:
         t.ver_tabla(tabla_vista, "Select * from vistaproducto Where marca Like '%" + con_Marca.getText()+"%';");
         t.ver_tabla(tabla_vista, "Select * from vistaproducto Where marca Like '%" + con_Marca.getText()+"%';");
    }//GEN-LAST:event_con_MarcaKeyTyped

    private void con_TipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_con_TipoItemStateChanged
        // TODO add your handling code here:
        if (con_Tipo.getSelectedIndex()>0) {
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where tipo = '" + con_Tipo.getSelectedItem().toString()+"';");
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where tipo = '" + con_Tipo.getSelectedItem().toString()+"';");
        }else{
        
        actualizar_tabla();
        }
        
    }//GEN-LAST:event_con_TipoItemStateChanged

    private void con_pesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_con_pesoStateChanged
        // TODO add your handling code here:
        if ((int)con_peso.getValue()<0) {
            con_peso.setValue(0);
        }
        if((int)con_peso.getValue()>0 && !con_peso.getValue().equals("")){
             t.ver_tabla(tabla_vista, "Select * from vistaproducto Where peso =" + con_peso.getValue()+";");
            }else{
            actualizar_tabla();
            }
        
    }//GEN-LAST:event_con_pesoStateChanged

    private void con_Nombre_Producto_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_Nombre_Producto_txtKeyReleased
        // TODO add your handling code here:
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where nombre like '%" + con_Nombre_Producto_txt.getText()+"%';");
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where nombre like '%" + con_Nombre_Producto_txt.getText()+"%';");
       
        
    }//GEN-LAST:event_con_Nombre_Producto_txtKeyReleased

    private void con_MarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_con_MarcaKeyReleased
        // TODO add your handling code here:
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where marca Like '%" + con_Marca.getText()+"%';");
        t.ver_tabla(tabla_vista, "Select * from vistaproducto Where marca Like '%" + con_Marca.getText()+"%';"); 
        
    }//GEN-LAST:event_con_MarcaKeyReleased

    private void con_PrecioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_con_PrecioStateChanged
        // TODO add your handling code here:
        
        if ((int)con_Precio.getValue()<0) {
            con_Precio.setValue(0);
        }
        
        if((int)con_Precio.getValue()>0){
             t.ver_tabla(tabla_vista, "Select * from vista_producto Where precio =" + con_Precio.getValue()+";");
            }else{
            actualizar_tabla();
            }
    }//GEN-LAST:event_con_PrecioStateChanged
    public static Connection con=null;
    public void reporte(boolean nombreProducto){
             //String url = "jdbc:sqlserver://DESKTOP-DMHSAF3:1433;databaseName=Bodega";
            //try {
                //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //String r = "C:\\Users\\kaito\\Desktop\\Proyecto_Bodega\\src\\proyecto_bodega\\reportePedidos.jasper";
            //con = DriverManager.getConnection(url,"Luiz","12345");
            //InputStream is = this.getClass().getClassLoader().getResourceAsStream(r);
            //JasperPrint j = JasperFillManager.fillReport(r, new HashMap(), con);
            //JasperViewer jv = new JasperViewer(j);
            //jv.setTitle("Pedidos completados");
            //jv.setVisible(true);
            
                //if (jv.isActive()) {
                //    System.out.println("proyecto_bodega.Pantalla.reporte()");
                //}
                    
                  //  } catch (Exception e) {
                       // System.out.println(e);
           // }
    
    }
 
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       tp.setVisible(true);
       tp.actualizarT();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alta_Marca;
    private javax.swing.JSpinner Alta_PEso;
    private javax.swing.JComboBox<String> Alta_Tipo;
    private javax.swing.JTextField Alta_nombreProducto;
    private javax.swing.JSpinner Alta_precio;
    private javax.swing.JPanel Altas;
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Consultas;
    private javax.swing.JPanel PanelCards;
    private javax.swing.JMenuItem Pedidos;
    private javax.swing.JMenuItem Refresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField con_Marca;
    private javax.swing.JTextField con_Nombre_Producto_txt;
    private javax.swing.JSpinner con_Precio;
    private javax.swing.JComboBox<String> con_Tipo;
    private javax.swing.JSpinner con_peso;
    private javax.swing.JRadioButton con_rb_NP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nombre25;
    private javax.swing.JLabel lbl_nombre26;
    private javax.swing.JLabel lbl_nombre27;
    private javax.swing.JLabel lbl_nombre28;
    private javax.swing.JLabel lbl_nombre29;
    private javax.swing.JRadioButton rb_marca;
    private javax.swing.JRadioButton rb_peso;
    private javax.swing.JRadioButton rb_precio;
    private javax.swing.JRadioButton rb_tipo;
    private javax.swing.JButton reset_button;
    private javax.swing.JTable tabla_vista;
    // End of variables declaration//GEN-END:variables


}
